module.exports = {
  globDirectory: ".",
  globPatterns: [
    "index.html",
    "offline.html",
    "css/main.css",
    "js/**/*.js",
    "data/**/*.js",
    "img/**/*.{png,svg,jpg,jpeg}",
    "pages/**/*.html",
    "manifest.json",
    "version.json",
  ],
  globIgnores: [
    "node_modules/**/*",
    "css/old_app.css",
    "css/old2_app.css",
    "src-sw.js",
    "workbox-config.js",
    "package.json",
    "package-lock.json",
    "README.md",
    "vitest.config.js",
    "tests/**/*",
    "scripts/**/*",
    ".github/**/*",
    ".gitignore",
  ],
  swSrc: "src-sw.js",
  swDest: "sw.js",
  maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
};
