"use strict";
// DO NOT EDIT public/sw.js — it is generated by npm run build:sw

importScripts("https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-sw.js");

function handleInstall(event) {
  event.waitUntil(self.skipWaiting());
}

function handleActivate(event) {
  event.waitUntil(
    Promise.all([
      self.clients.claim(),
      startVersionChecking(),
    ])
  );
}

function handleMessage(event) {
  if (event && event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  } else if (event && event.data && event.data.type === "TRIGGER_VERSION_CHECK") {
    checkForVersionUpdate();
  }
}

workbox.core.clientsClaim();

// This line is a placeholder. Workbox will replace it with the precache manifest.
workbox.precaching.precacheAndRoute(self.__WB_MANIFEST);

// Page Cache (Network First)
workbox.routing.registerRoute(
  ({ request }) => request.mode === "navigate",
  new workbox.strategies.NetworkFirst({
    cacheName: "pages",
    plugins: [
      new workbox.cacheableResponse.CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// Image Cache (Cache First)
workbox.routing.registerRoute(
  ({ request }) => request.destination === "image",
  new workbox.strategies.CacheFirst({
    cacheName: "images",
    plugins: [
      new workbox.expiration.ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 30 * 24 * 60 * 60 }),
      new workbox.cacheableResponse.CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
);

// Static Resources (Stale While Revalidate)
workbox.routing.registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new workbox.strategies.StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// Handle offline fallback
workbox.routing.setCatchHandler(({ event }) => {
  if (event.request.destination === "document") {
    return caches.match("/index.html");
  }
  return Response.error();
});

// Version checking for app updates
let versionCheckInterval;

// Get the correct base path for GitHub Pages deployment (must stay in sync with util.getBasePath)
function getBasePath() {
  // Check if we're on GitHub Pages
  const isGitHubPages = self.location.hostname.includes('github.io');

  if (isGitHubPages) {
    // Extract repository name from path
    const pathParts = self.location.pathname.split('/');
    const repoName = pathParts.length > 1 && pathParts[1] ? pathParts[1] : '';
    return repoName ? `/${repoName}` : '';
  }

  // For local development or other deployments
  return '';
}

function startVersionChecking() {
  // Clear any existing interval
  if (versionCheckInterval) {
    clearInterval(versionCheckInterval);
  }

  // Check for new version every 2 minutes
  versionCheckInterval = setInterval(async () => {
    await checkForVersionUpdate();
  }, 2 * 60 * 1000); // 2 minutes
}

async function checkForVersionUpdate() {
  try {
    // Get local version first
    const localVersion = await getCurrentVersion();
    if (!localVersion) {
      console.log("No local version found, skipping check");
      return;
    }

    // Check deployed version
    const deployedVersion = await getDeployedVersion();
    if (!deployedVersion) {
      console.log("Could not fetch deployed version");
      return;
    }

    console.log(`Version check: Local=${localVersion}, Deployed=${deployedVersion}`);

    if (deployedVersion !== localVersion) {
      notifyClientsOfNewVersion(deployedVersion, localVersion);
    }
  } catch (error) {
    console.log("Version check failed:", error);
  }
}

function handleNotificationClick(event) {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        let client = clientList[0];
        for (let i = 0; i < clientList.length; i++) {
          if (clientList[i].focused) {
            client = clientList[i];
          }
        }
        return client.focus();
      }
      return self.clients.openWindow(event.notification.data.url || "/");
    })
  );
}

async function getDeployedVersion() {
  try {
    const basePath = getBasePath();
    const versionUrl = `${self.location.origin}${basePath}/version.json`;
    // The cache: "no-cache" header is the most important part here.
    const response = await fetch(versionUrl, { cache: "no-cache" });

    if (response.ok) {
      const versionData = await response.json();
      return versionData.version;
    }
  } catch (error) {
    console.log("Failed to get deployed version:", error);
  }
  return null;
}

async function getCurrentVersion() {
  try {
    const basePath = getBasePath();
    const versionUrl = `${self.location.origin}${basePath}/version.json`;
    let response = null;
    if (typeof workbox !== "undefined" && workbox.precaching && workbox.precaching.getCacheKeyForURL) {
      const cacheKey = workbox.precaching.getCacheKeyForURL(versionUrl);
      if (cacheKey) {
        const cacheNames = await caches.keys();
        for (const name of cacheNames) {
          const cache = await caches.open(name);
          response = await cache.match(cacheKey);
          if (response) break;
        }
      }
    }
    if (!response) {
      const cacheNames = await caches.keys();
      for (const name of cacheNames) {
        const cache = await caches.open(name);
        response = await cache.match(versionUrl);
        if (response) break;
      }
    }
    if (!response) {
      response = await fetch(versionUrl, { cache: "force-cache" });
    }
    if (response && response.ok) {
      const data = await response.json();
      return data.version;
    }
  } catch (error) {
    console.log("Failed to get current version:", error);
  }
  return null;
}

function notifyClientsOfNewVersion(newVersion, currentVersion) {
  self.clients.matchAll().then((clients) => {
    clients.forEach((client) => {
      client.postMessage({
        type: "NEW_VERSION_AVAILABLE",
        version: newVersion,
        currentVersion: currentVersion,
      });
    });
  });
}

async function handlePeriodicSync() {
  try {
    // Use the same version checking logic as the interval
    await checkForVersionUpdate();
  } catch (e) {
    // Silent fail; periodic sync will retry later
    console.log("Periodic sync failed:", e);
  }
}

function handlePeriodicSyncEvent(event) {
  if (event.tag === "reactor-periodic-sync") {
    event.waitUntil(handlePeriodicSync());
  }
}

function handleSyncEvent(event) {
  if (event.tag === "reactor-sync") {
    event.waitUntil(handlePeriodicSync());
  }
}

function unregisterServiceWorkerListeners() {
  self.removeEventListener("install", handleInstall);
  self.removeEventListener("activate", handleActivate);
  self.removeEventListener("message", handleMessage);
  self.removeEventListener("notificationclick", handleNotificationClick);
  self.removeEventListener("periodicsync", handlePeriodicSyncEvent);
  self.removeEventListener("sync", handleSyncEvent);
  if (versionCheckInterval) {
    clearInterval(versionCheckInterval);
    versionCheckInterval = null;
  }
}

function registerServiceWorkerListeners() {
  unregisterServiceWorkerListeners();
  self.addEventListener("install", handleInstall);
  self.addEventListener("activate", handleActivate);
  self.addEventListener("message", handleMessage);
  self.addEventListener("notificationclick", handleNotificationClick);
  self.addEventListener("periodicsync", handlePeriodicSyncEvent);
  self.addEventListener("sync", handleSyncEvent);
}

registerServiceWorkerListeners();